# 연습문제

### 1

In [1]:
import numpy as np

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 2번

In [3]:
#a = np.array([1 if i == 4 else 0 for i in range(10)])
a = np.eye(10,dtype=int)[4]
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 3번

In [4]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4번

In [5]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 5번

In [6]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6번

In [7]:
a = np.array([1,2,0,0,4,0])
a[a!=0]

array([1, 2, 4])

### 7번

In [8]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8번

In [9]:
a = np.random.rand(9).reshape(3,3)
a

array([[0.60775347, 0.79438504, 0.32416121],
       [0.70048782, 0.33213209, 0.01137134],
       [0.86643218, 0.39831542, 0.83929598]])

### 9번

In [10]:
a.max(),a.min()

(0.8664321816263494, 0.011371341597320894)

### 10번

In [11]:
a.mean(axis=1), a.mean(axis=0)

(array([0.78460784, 0.34791666, 0.55625076]),
 array([0.45114178, 0.46494175, 0.77269174]))