# Numpy Array

## Numpy Array  

In [1]:
# 리스트와 넘파이 어레이 속도 비결
import numpy as np 
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [10]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 150 ms


In [11]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 5 ms


In [31]:
ar = np.array(list(range(10)))
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
type(ar)

numpy.ndarray

In [33]:
ar.shape

(10,)

In [37]:
al = [2*i for i in range(1,11)]
al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [38]:
2*ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
a = np.array(list(range(1,4)))
b = np.array(list(range(10,40,10)))
print('a = ',a,'b = ',b)

a =  [1 2 3] b =  [10 20 30]


In [41]:
2*a+b

array([12, 24, 36])

In [46]:
a == 2

array([False,  True, False])

In [47]:
b>10

array([False,  True,  True])

In [48]:
(a==2)&(b>10)

array([False,  True, False])

In [56]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
c.shape

(2, 3)

In [58]:
len(c)

2

In [59]:
len(c[0])

3

In [61]:
c = np.array([[10,20,30,40],[50,60,70,80]])
print(c)

[[10 20 30 40]
 [50 60 70 80]]


In [74]:
np.arange(10,90,10).reshape(4,-1)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [105]:
d = np.array(np.arange(1,13).reshape(3,4))
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
x = np.arange(1,21)
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [107]:
x[x%4 == 1]

array([ 1,  5,  9, 13, 17])

In [109]:
x[(x%3 == 0) & (x % 4 == 1)]

array([9])

In [110]:
a = np.arange(5)
a[2]

2

In [111]:
a[-1]

4

In [114]:
a = np.arange(6).reshape(2,-1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [113]:
a[1,0]

3

In [115]:
a = np.arange(8).reshape(2,-1)

In [116]:
a[:,1:3]

array([[1, 2],
       [5, 6]])

In [119]:
m = np.arange(15).reshape(3,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [120]:
m[1,2]

7

In [128]:
m[2:,4:]

array([[14]])

In [131]:
m[1,1:3]

array([6, 7])

In [132]:
m[1:,2]

array([ 7, 12])

In [133]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [134]:
a = np.arange(10)
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [135]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [136]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [137]:
a = np.arange(11,100,11)

In [139]:
a[a%2!=0]

array([11, 33, 55, 77, 99])

In [142]:
a = np.arange(1,13).reshape(3,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
a[:,[True,False,True,False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])