# 배열의 생성과 변형

In [2]:
import numpy as np

In [7]:
x = np.arange(1,4)
x.dtype

dtype('int32')

In [8]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [10]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [12]:
x = np.array([1,2,3],dtype = 'float32')
x.dtype

dtype('float32')

### Inf와 Nan 

In [13]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

array([  0.,  inf, -inf,  nan])

In [14]:
np.log(0)

-inf

In [15]:
np.exp(-np.inf)

0.0

### 배열생성

In [25]:
np.zeros(5),np.zeros(5).dtype

(array([0., 0., 0., 0., 0.]), dtype('float64'))

In [27]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
c = np.zeros((5,2),dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.ones_like(b)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
g = np.empty((4,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [50]:
x = np.linspace(-5,5,100)
y = 1/(1+np.exp(-x)

In [51]:
np.log(np.logspace(0.1,1,10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

### 전치연산 (Transpose)

In [3]:
A = np.arange(1,7).reshape(2,-1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [6]:
A @ A.T

array([[14, 32],
       [32, 77]])

### 배열의 크기 변경

In [14]:
a = np.arange(12)
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
a.reshape(3,2,-1)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [17]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a.reshape(3,2,-1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [24]:
x = np.arange(5)
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [25]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [26]:
x.reshape(5,1,1)

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [28]:
k = x.reshape(1,5) @ x.reshape(5,1)
k.shape

(1, 1)

In [30]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [31]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.vstack([b1,b2]).shape

(5, 3)

In [36]:
a = np.zeros((3,3))
b = np.ones((3,2))
ab = np.hstack([a,b])
ab

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [39]:
c = np.arange(10,160,10).reshape(3,5)

In [41]:
x = np.vstack([ab,c,ab,c])
x

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [42]:
x = np.arange(3)
y = np.arange(5)
X,Y = np.meshgrid(x,y)
[list(zip(x,y))for x,y in zip(X,Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]