# 배열의 연산

In [1]:
import numpy as np 

In [5]:
%%time
x = np.arange(1,10001)
y = np.arange(10001,20001)
z = x+y
z[:10]

Wall time: 999 µs


array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [6]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [7]:
np.all(a==b)

False

In [8]:
np.all(a==c)

True

In [13]:
a=np.arange(10)
np.log10(a+1)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

### 스칼라와 벡터/행렬의 곱셈

In [16]:
x=np.arange(10)
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [17]:
x = np.arange(12).reshape(3,4)
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드캐스팅

In [19]:
x = np.arange(5)
y = np.ones_like(x)
x+y

array([1, 2, 3, 4, 5])

In [20]:
x+1

array([1, 2, 3, 4, 5])

### 차원 축소 연산

In [21]:
x = np.arange(1,5)

In [24]:
x.sum()

10

In [25]:
x.min()

1

In [26]:
x.argmax()

3

In [27]:
x = np.array([[2,4],[3,6]])

In [29]:
x.sum(axis=0)

array([ 5, 10])

In [30]:
x.sum(axis=1)

array([6, 9])

In [32]:
a = np.arange(30).reshape(5,-1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
x = np.linspace(1.0,10.0,30).reshape(5,6).round(2)
print(x)

[[ 1.    1.31  1.62  1.93  2.24  2.55]
 [ 2.86  3.17  3.48  3.79  4.1   4.41]
 [ 4.72  5.03  5.34  5.66  5.97  6.28]
 [ 6.59  6.9   7.21  7.52  7.83  8.14]
 [ 8.45  8.76  9.07  9.38  9.69 10.  ]]


In [40]:
# 1
x.max()

10.0

In [41]:
# 2
x.sum(axis = 1)

array([10.65, 21.81, 33.  , 44.19, 55.35])

In [42]:
# 3
x.max(axis = 1)

array([ 2.55,  4.41,  6.28,  8.14, 10.  ])

In [48]:
# 4
np.mean(x,axis = 0)

array([4.724, 5.034, 5.344, 5.656, 5.966, 6.276])

In [47]:
# 5
x.min(axis=0)

array([1.  , 1.31, 1.62, 1.93, 2.24, 2.55])

### 정렬

In [49]:
a=np.array([[4,3,5,7],[1,12,11,9],[2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [50]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [52]:
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [53]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [55]:
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [56]:
a.sort(axis = 0)
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])