# 난수 발생과 카운팅

In [2]:
import numpy as np 

### 시드 설정하기

In [5]:
np.random.rand(5)

array([0.36519271, 0.68912374, 0.8608703 , 0.77547999, 0.71947148])

In [6]:
np.random.rand(5)

array([0.3620558 , 0.99484806, 0.27825539, 0.560332  , 0.42281251])

In [7]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [8]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터 순서 바꾸기

In [10]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.shuffle(x) # 자체 변환 함수 주의
x

array([2, 0, 4, 5, 7, 8, 6, 3, 1, 9])

In [32]:
np.random.choice(x,3,replace=True)

array([9, 2, 9])

In [33]:
np.random.choice(5,3,p=[0,0,0,0,1])

array([4, 4, 4])

### 난수생성

In [36]:
np.random.rand(5)

array([0.74062739, 0.85105865, 0.63984529, 0.72377434, 0.65938213])

In [37]:
np.random.randn(10)

array([ 0.76973631,  1.19852089,  0.76367794,  1.04308638,  0.71284852,
        0.64679522,  0.83032147,  1.36407158, -0.32562884, -0.2826132 ])

In [44]:
np.random.randint(2,size=4)

array([0, 1, 0, 1])

In [50]:
price = 10000
tomorrow = price *(1 + np.random.randn(1)/100) 
tomorrow

array([10063.01217867])

In [56]:
prices = []
price = 10000
for i in range(250):
    k = np.random.randn(1)/100
    tmp *= price*(1+k)
    price = tmp[0]
    prices.append(price)
price[:10]
    


IndexError: index 0 is out of bounds for axis 0 with size 0

### 정수 데이터 카운팅

In [58]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [59]:
a = np.array(['a','b','b','c','a'])
index,count = np.unique(a,return_counts=True)

In [60]:
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))