# 벡터와 벡터의 곱셈

In [1]:
import numpy as np

In [5]:
x = np.arange(1,4).reshape(3,1)
y = np.arange(4,7).reshape(3,1)
x,y
 

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [6]:
x.shape,y.shape

((3, 1), (3, 1))

In [7]:
x.T.shape

(1, 3)

In [8]:
z = x.T @ y
z

array([[32]])

In [9]:
np.dot(x.T,y)

array([[32]])

In [10]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
x = np.arange(4).reshape(2,2)
y = np.arange(5,9).reshape(2,2)
x.shape[0]

2

In [39]:
p = np.array([100,80,50])
n = np.array([3,4,5])
p@n

870

(array([100,  80,  50]), array([100,  80,  50]))

In [42]:
a = np.arange(10,81,10).reshape(2,-1)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [59]:
a = np.array([1 if i == 4 else 0 for i in range(10)])
b = np.eye(10,dtype = int)[4]
a,b

(array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]))