# 연습문제

### 1

In [3]:
import numpy as np

In [45]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 2번

In [49]:
#a = np.zeros(4)
#b = np.ones(1)
#c = np.zeros(5)
#np.hstack((a,b,c))
a = np.zeros(10)
a[5] = 1
a

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### 3번

In [17]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4번

In [24]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 5번

In [28]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6번

In [33]:
a = np.array([1,2,0,0,4,0])
a[a!=0]

array([1, 2, 4])

### 7번

In [37]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8번

In [39]:
a = np.random.rand(9).reshape(3,3)
a

array([[0.50069962, 0.75050653, 0.71514017],
       [0.45528046, 0.45236009, 0.39813203],
       [0.3688517 , 0.62780398, 0.0372205 ]])

### 9번

In [41]:
a.max(),a.min()

(0.7505065347357472, 0.037220497296160726)

### 10번

In [44]:
a.mean(axis=1), a.mean(axis=0)

(array([0.65544877, 0.43525753, 0.34462539]),
 array([0.44161059, 0.61022353, 0.38349757]))